"""test1

Revision ID: 0edf0a83b569
Revises: 229c84671864
Create Date: 2024-12-06 14:12:19.603806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0edf0a83b569'
down_revision: Union[str, None] = '229c84671864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pity_report', sa.Column('executor', sa.INTEGER(), nullable=True))
    op.add_column('pity_report', sa.Column('env', sa.INTEGER(), nullable=False))
    op.add_column('pity_report', sa.Column('cost', sa.String(length=8), nullable=True))
    op.add_column('pity_report', sa.Column('plan_id', sa.INTEGER(), nullable=True))
    op.add_column('pity_report', sa.Column('start_at', sa.DATETIME(), nullable=False))
    op.add_column('pity_report', sa.Column('finished_at', sa.DATETIME(), nullable=True))
    op.add_column('pity_report', sa.Column('success_count', sa.INTEGER(), nullable=False))
    op.add_column('pity_report', sa.Column('error_count', sa.INTEGER(), nullable=False))
    op.add_column('pity_report', sa.Column('failed_count', sa.INTEGER(), nullable=False))
    op.add_column('pity_report', sa.Column('skipped_count', sa.INTEGER(), nullable=False))
    op.add_column('pity_report', sa.Column('status', mysql.SMALLINT(), nullable=False, comment='0: pending, 1: running, 2: stopped, 3: finished'))
    op.add_column('pity_report', sa.Column('mode', mysql.SMALLINT(), nullable=True, comment='0: 手动, 1: 自动, 2: 测试集, 3: pipeline, 4: 其他'))
    op.add_column('pity_report', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_pity_report_deleted_at'), 'pity_report', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pity_report_executor'), 'pity_report', ['executor'], unique=False)
    op.create_index(op.f('ix_pity_report_plan_id'), 'pity_report', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pity_report_status'), 'pity_report', ['status'], unique=False)
    op.add_column('pity_test_result', sa.Column('case_name', sa.String(length=32), nullable=True))
    op.add_column('pity_test_result', sa.Column('request_headers', sa.TEXT(), nullable=True))
    op.add_column('pity_testcase', sa.Column('request_headers', sa.TEXT(), nullable=True, comment='请求头，可为空'))
    op.drop_column('pity_testcase', 'request_header')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pity_testcase', sa.Column('request_header', mysql.TEXT(), nullable=True, comment='请求头，可为空'))
    op.drop_column('pity_testcase', 'request_headers')
    op.drop_column('pity_test_result', 'request_headers')
    op.drop_column('pity_test_result', 'case_name')
    op.drop_index(op.f('ix_pity_report_status'), table_name='pity_report')
    op.drop_index(op.f('ix_pity_report_plan_id'), table_name='pity_report')
    op.drop_index(op.f('ix_pity_report_executor'), table_name='pity_report')
    op.drop_index(op.f('ix_pity_report_deleted_at'), table_name='pity_report')
    op.drop_column('pity_report', 'deleted_at')
    op.drop_column('pity_report', 'mode')
    op.drop_column('pity_report', 'status')
    op.drop_column('pity_report', 'skipped_count')
    op.drop_column('pity_report', 'failed_count')
    op.drop_column('pity_report', 'error_count')
    op.drop_column('pity_report', 'success_count')
    op.drop_column('pity_report', 'finished_at')
    op.drop_column('pity_report', 'start_at')
    op.drop_column('pity_report', 'plan_id')
    op.drop_column('pity_report', 'cost')
    op.drop_column('pity_report', 'env')
    op.drop_column('pity_report', 'executor')
    # ### end Alembic commands ###
