"""test

Revision ID: 229c84671864
Revises: 
Create Date: 2024-11-29 13:38:43.798518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '229c84671864'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_project_name', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_project_role_project_id', table_name='project_role')
    op.drop_index('ix_project_role_project_role', table_name='project_role')
    op.drop_table('project_role')
    op.drop_index('ix_test_case_name', table_name='test_case')
    op.drop_table('test_case')
    op.drop_index('name', table_name='pity_environment')
    op.create_unique_constraint(None, 'pity_environment', ['name', 'deleted_at'])
    op.add_column('pity_user', sa.Column('avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pity_user', 'avatar')
    op.drop_constraint(None, 'pity_environment', type_='unique')
    op.create_index('name', 'pity_environment', ['name'], unique=True)
    op.create_table('test_case',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('request_type', mysql.INTEGER(), autoincrement=False, nullable=True, comment='请求类型 1: http 2: grpc 3: dubbo'),
    sa.Column('url', mysql.TEXT(), nullable=False, comment='请求url'),
    sa.Column('request_method', mysql.VARCHAR(length=12), nullable=True, comment='请求方式, 如果非http可为空'),
    sa.Column('request_header', mysql.TEXT(), nullable=True, comment='请求头，可为空'),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='所属项目'),
    sa.Column('tag', mysql.VARCHAR(length=64), nullable=True, comment='用例标签'),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True, comment='用例状态: 1: 待完成 2: 暂时关闭 3: 正常运作'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('create_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('update_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('params', mysql.TEXT(), nullable=True, comment='请求params'),
    sa.Column('body', mysql.TEXT(), nullable=True, comment='请求body'),
    sa.Column('priority', mysql.VARCHAR(length=3), nullable=True, comment='用例优先级p0-p3'),
    sa.Column('catalogue', mysql.VARCHAR(length=12), nullable=True, comment='用例目录'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_test_case_name', 'test_case', ['name'], unique=True)
    op.create_table('project_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_role', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('create_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_project_role_project_role', 'project_role', ['project_role'], unique=False)
    op.create_index('ix_project_role_project_id', 'project_role', ['project_id'], unique=False)
    op.create_table('project',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('owner', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('create_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('app', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_project_name', 'project', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=True, comment='0: 普通用户 1: 组长 2: 超级管理员'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
